version: "3"

services: 
    
    personal_website:
        build: ./images/apache/
        hostname: personal_website
        container_name: personal_website
        volumes: 
            - ../docs:/var/www/html
        networks:
            - personal_website_network
        expose:
            - "80"
        ports:
            - "80:80"
            
networks:
    personal_website_network:
